CREATE TABLE DEPARTMENT (
    DEPT_ID     INT PRIMARY KEY,
    DEPT_NAME   VARCHAR(100) NOT NULL
);

CREATE TABLE SUBJECT (
    SUBJECT_ID       INT PRIMARY KEY,
    SUBJECT_NAME     VARCHAR(100) NOT NULL,
    OFFERED_SEMESTER INT NOT NULL,
    DEPT_ID          INT NOT NULL,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE STUDENTS (
    STUDENT_ID       INT PRIMARY KEY,
    FNAME            VARCHAR(50) NOT NULL,
    MNAME            VARCHAR(50),
    LNAME            VARCHAR(50) NOT NULL,
    CURRENT_SEMESTER INT NOT NULL,
    DEPT_ID          INT NOT NULL,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE EXAMINATION (
    EXAM_ID     INT PRIMARY KEY,
    SUBJECT_ID  INT NOT NULL,
    EXAM_DATE   DATE NOT NULL,
    START_TIME  TIME NOT NULL,
    END_TIME    TIME NOT NULL,
    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID)
);

-- DURATION = END_TIME - START_TIME, computed at query time or as a generated column

CREATE TABLE ROOMS (
    ROOM_ID   INT PRIMARY KEY,
    BUILDING  VARCHAR(50),
    FLOOR     VARCHAR(10),
    CAPACITY  INT NOT NULL,
    STATUS    VARCHAR(20) DEFAULT 'AVAILABLE'
);

CREATE TABLE INVIGILATOR (
    INVIGILATOR_ID   INT PRIMARY KEY,
    INVIGILATOR_NAME VARCHAR(100) NOT NULL,
    PHONE            VARCHAR(20),
    EMAIL            VARCHAR(100)
);

CREATE TABLE EXAM_REGISTRATION (
    REGISTR_ID    INT PRIMARY KEY,
    STUDENT_ID    INT NOT NULL,
    EXAM_ID       INT NOT NULL,
    REGISTR_DATE  DATE NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (EXAM_ID) REFERENCES EXAMINATION(EXAM_ID),
    UNIQUE (STUDENT_ID, EXAM_ID)
);

CREATE TABLE ROOM_ALLOCATION (
    ALLOCATION_ID INT PRIMARY KEY,
    REGISTR_ID    INT NOT NULL UNIQUE,
    ROOM_ID       INT NOT NULL,
    SEAT_NO       VARCHAR(10) NOT NULL,
    FOREIGN KEY (REGISTR_ID) REFERENCES EXAM_REGISTRATION(REGISTR_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID),
    UNIQUE (ROOM_ID, SEAT_NO)
);

CREATE TABLE INVIGILATOR_DUTY (
    DUTY_ID         INT PRIMARY KEY,
    EXAM_ID         INT NOT NULL,
    INVIGILATOR_ID  INT NOT NULL,
    ROOM_ID         INT NOT NULL,
    ASSIGNED_ON     DATE NOT NULL,
    FOREIGN KEY (EXAM_ID) REFERENCES EXAMINATION(EXAM_ID),
    FOREIGN KEY (INVIGILATOR_ID) REFERENCES INVIGILATOR(INVIGILATOR_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID),
    UNIQUE (EXAM_ID, INVIGILATOR_ID, ROOM_ID)
);
